%YAML 1.1
---
gfVersion: v1.0
class: workflow

# metadata
name: Hello World Workflow
description: Hello World one-step workflow
documentation_uri: 
repo_uri: 'https://github.com/jhphan/hello-world-workflow-gf.git'
version: '0.3'
username: user

final_output:
- hello

# inputs
inputs:
  file:
    label: Input Text File
    description: Input text file
    type: File
    enable: true
    visible: true

# parameters
parameters:

# steps
steps:
  hello:
    app: apps/hello-world-gf-0.3/app.yaml
    depend: []
    template:
      file: '{workflow->file}'
      output: output.txt
...
